export const CreateHotelFormData = [
  {
    name: "hotel-name",
    type: "text",
    placeholder: "Enter Hotel Name",
    label: "Hotel Name",
  },
  {
    name: "price-per-night",
    type: "text",
    placeholder: "Enter Price/Night",
    label: "Price Per Night",
  },
  {
    name: "room-type-1",
    type: "text",
    placeholder: "Enter Room Type",
    label: "Room Type",
    incremental: true,
  },
  {
    name: "room-type-2",
    type: "text",
    placeholder: "Enter Room Type",
    label: "Room Type",
    incremental: true,
  },
  {
    name: "room-type-3",
    type: "text",
    placeholder: "Enter Room Type",
    label: "Room Type",
    incremental: true,
  },
  {
    name: "hotel-address",
    type: "text",
    placeholder: "Enter Hotel Address",
    label: "Hotel Address",
  },
  {
    name: "hotel-mobile",
    type: "text",
    placeholder: "Enter Hotel Mobile",
    label: "Hotel Mobile",
  },
  {
    name: "description",
    type: "textarea",
    placeholder: "Enter Description",
    label: "Description",
  },
  {
    name: "nearby-place-1",
    type: "text",
    placeholder: "Enter Nearby Place 1",
    label: "Nearby Place 1",
    incremental: true,
  },
  {
    name: "nearby-place-2",
    type: "text",
    placeholder: "Enter Nearby Place 2",
    label: "Nearby Place 2",
    incremental: true,
  },
  {
    name: "nearby-place-3",
    type: "text",
    placeholder: "Enter Nearby Place 3",
    label: "Nearby Place 3",
    incremental: true,
  },
  {
    name: "map-link",
    type: "text",
    placeholder: "Enter Map Link",
    label: "Map Link",
  },
];
