export const CreateHotelFormData = [
  {
    name: "hotelName",
    type: "text",
    placeholder: "Enter Hotel Name",
    label: "Hotel Name",
  },
  {
    name: "pricePerNight",
    type: "number",
    placeholder: "Enter Price/Night",
    label: "Price Per Night",
  },
  {
    name: "roomType1",
    type: "text",
    placeholder: "Enter Room Type",
    label: "Room Type",
  },
  {
    name: "roomType1Price",
    type: "number",
    placeholder: "Enter Room Type Price",
    label: "Room Type Price",
  },
  {
    name: "roomType2",
    type: "text",
    placeholder: "Enter Room Type",
    label: "Room Type",
  },
  {
    name: "roomType2Price",
    type: "number",
    placeholder: "Enter Room Type Price",
    label: "Room Type Price",
  },
  {
    name: "roomType3",
    type: "text",
    placeholder: "Enter Room Type",
    label: "Room Type",
  },
  {
    name: "roomType3Price",
    type: "number",
    placeholder: "Enter Room Type Price",
    label: "Room Type Price",
  },
  {
    name: "hotelAddress",
    type: "text",
    placeholder: "Enter Hotel Address",
    label: "Hotel Address",
  },
  {
    name: "hotelMobile",
    type: "number",
    placeholder: "Enter Hotel Mobile",
    label: "Hotel Mobile",
  },
  {
    name: "description",
    type: "textarea",
    placeholder: "Enter Description",
    label: "Description",
  },
  {
    name: "nearbyPlace1",
    type: "text",
    placeholder: "Enter Nearby Place 1",
    label: "Nearby Place 1",
  },
  {
    name: "nearbyPlace1Dist",
    type: "number",
    placeholder: "Enter Nearby Place 1 Distance",
    label: "Nearby Place 1 Distance",
  },
  {
    name: "nearbyPlace2",
    type: "text",
    placeholder: "Enter Nearby Place 2",
    label: "Nearby Place 2",
  },
  {
    name: "nearbyPlace2Dist",
    type: "number",
    placeholder: "Enter Nearby Place 2 Distance",
    label: "Nearby Place 2 Distance",
  },
  {
    name: "nearbyPlace3",
    type: "text",
    placeholder: "Enter Nearby Place 3",
    label: "Nearby Place 3",
  },
  {
    name: "nearbyPlace3Dist",
    type: "number",
    placeholder: "Enter Nearby Place 3 Distance",
    label: "Nearby Place 3 Distance",
  },
  {
    name: "mapLink",
    type: "text",
    placeholder: "Enter Map Link",
    label: "Map Link",
  },
];
